public class Main {
    public static void main(String[] args) {
        System.out.println("----- Ex 22: Perfect Number -----");
        System.out.println(PerfectNumber.isPerfectNumber(6));
        System.out.println(PerfectNumber.isPerfectNumber(28));
        System.out.println(PerfectNumber.isPerfectNumber(5));
        System.out.println(PerfectNumber.isPerfectNumber(-1));
        System.out.println("----- END -----\n");
        System.out.println("----- Ex 23: Number To Words -----");
        System.out.println(NumberToWords.getDigitCount(0));
        System.out.println(NumberToWords.getDigitCount(123));
        System.out.println(NumberToWords.getDigitCount(-12));
        System.out.println(NumberToWords.getDigitCount(5200));
        System.out.println(NumberToWords.reverse(-121));
        System.out.println(NumberToWords.reverse(1212));
        System.out.println(NumberToWords.reverse(1234));
        System.out.println(NumberToWords.reverse(100));
        NumberToWords.numberToWords(100);
        NumberToWords.numberToWords(1000);
        System.out.println("----- END -----\n");
        System.out.println("----- Ex 24: Flour Pack Problem -----");
        System.out.println(FlourPacker.canPack(2, 0, 9));
        System.out.println(FlourPacker.canPack(1, 0, 4));
        System.out.println(FlourPacker.canPack(1, 0, 5));
        System.out.println(FlourPacker.canPack(2, 2, 11));
        System.out.println(FlourPacker.canPack(-3, 2, 12));
        System.out.println(FlourPacker.canPack(0, 5, 5));
        System.out.println("----- END -----\n");
        System.out.println("----- Ex 25:Largest Prime -----");
        System.out.println(LargestPrime.getLargestPrime(21));
        System.out.println(LargestPrime.getLargestPrime(217));
        System.out.println(LargestPrime.getLargestPrime(0));
        System.out.println(LargestPrime.getLargestPrime(45));
        System.out.println(LargestPrime.getLargestPrime(-1));
        System.out.println(LargestPrime.getLargestPrime(7));
        System.out.println("----- END -----\n");
        System.out.println("----- Ex 26:Diagonal Star -----");
        DiagonalStar.printSquareStar(8);
        DiagonalStar.printSquareStar(5);
        DiagonalStar.printSquareStar(10);
        DiagonalStar.printSquareStar(15);
        System.out.println("----- END -----\n");
        System.out.println("----- Ex 27: Input Calculator -----");
//        InputCalculator.inputThenPrintSumAndAverage();
        System.out.println("----- END -----\n");
        System.out.println("----- Ex 28: Paint Job -----");
        System.out.println(PaintJob.getBucketCount(-3.4, 2.1, 1.5, 2));
        System.out.println(PaintJob.getBucketCount(3.4, 2.1, 1.5, 2));
        System.out.println(PaintJob.getBucketCount(2.75, 3.25, 2.5, 1));
        System.out.println(PaintJob.getBucketCount(-3.4, 2.1, 1.5));
        System.out.println(PaintJob.getBucketCount(3.4, 2.1, 1.5));
        System.out.println(PaintJob.getBucketCount(7.25, 4.3, 2.35));
        System.out.println(PaintJob.getBucketCount(3.4, 1.5));
        System.out.println(PaintJob.getBucketCount(6.26, 2.2));
        System.out.println(PaintJob.getBucketCount(3.26, 0.75));
        System.out.println("----- END -----\n");
    }
}
